import type { Metadata } from "next";
import dynamic from "next/dynamic";
import Image from "next/image";
import { Footer } from "@/components/Footer";
import sitesData from "@/content/websites.json";
import profile from "@/content/profile.json";
import styles from "./work.module.css";
const Orbit=dynamic(()=>import("@/components/WorkOrbit"),{loading:()=> <p>Preparing the orbit...</p>});
export const metadata:Metadata={title:"Work Orbit",description:"Eighteen approved websites and a focused Swawlambi operations case file."};
export default function Work(){return <><main id="main"><section className={styles.hero}><div className="shell"><p className="eyebrow">18 sites / one working practice</p><h1 className="display">Work Orbit</h1><p>A navigable record of websites created or contributed to. No unverified performance results are attached.</p><Orbit/></div></section><section className="section"><div className="shell"><p className="eyebrow">Accessible flight manifest</p><h2 className="display">Every site, within reach.</h2><ol className={styles.manifest}>{sitesData.sites.map((site,i)=><li key={site.id}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{site.name}</h3><p>{site.category}</p></div><a className="button" href={site.url} target="_blank" rel="noreferrer">Visit site<span className="srOnly">: {site.name}</span></a></li>)}</ol></div></section><section className={`${styles.swawlambi} section`}><div className="shell"><div className={styles.caseHead}><Image src="/assets/swawlambi-logo.jpg" alt="Swawlambi Inc. logo" width={260} height={260}/><div><p className="eyebrow">Operational case file</p><h2 className="display">Where power meets purpose.</h2><p>{profile.work[0].summary}</p></div></div><div className={styles.services}>{profile.swawlambi.services.map((x,i)=><article key={x}><span>Field note {String(i+1).padStart(2,"0")}</span><h3>{x}</h3><p>Part of Swawlambi&apos;s confirmed service scope. No client outcome is claimed.</p></article>)}</div><div className={styles.claims}>{profile.swawlambi.companyReportedClaims.map(c=><div key={c.label}><strong>{c.value}</strong><p>{c.label}</p><small>{c.requiredDisclosure}</small></div>)}</div><div className={styles.map}><div><h3>Office coordinates</h3><address>{profile.swawlambi.address}</address><a className="button" href={profile.swawlambi.map.shortUrl} target="_blank" rel="noreferrer">Get directions</a></div><iframe title="Map showing the Swawlambi office in Inderlok, Delhi" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q=28.6690016,77.1686023&z=17&output=embed"/></div></div></section></main><Footer/></>}
