"use client";
import { useEffect, useRef } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import profile from "@/content/profile.json";
import styles from "./HomeStory.module.css";

function Footballer(){return <svg className={styles.playerSvg} viewBox="0 0 300 310" role="img" aria-label="Illustrated left winger juggling a football while looking at his phone"><g className={styles.body}><circle cx="154" cy="55" r="30" fill="#b56e43" stroke="currentColor" strokeWidth="5"/><path d="M126 45c6-31 54-34 60 0-17-12-38-13-60 0Z" fill="#171713"/><path d="M117 94 86 177l43 29 59-4 23-99-44-22Z" fill="#f1e9da" stroke="currentColor" strokeWidth="5"/><path d="m137 92 17 51 20-54" fill="none" stroke="#cc861b" strokeWidth="9"/><path d="m124 112-48 20 13 54M190 111l30 45 17-18" fill="none" stroke="currentColor" strokeWidth="16"/><rect x="221" y="119" width="24" height="38" fill="#2455b5" stroke="currentColor" strokeWidth="4"/><path d="m129 204-31 68M174 204l37 68" fill="none" stroke="currentColor" strokeWidth="19"/><path d="m75 277 34-2M199 278l35 1" stroke="currentColor" strokeWidth="13"/></g><g className={styles.ball}><circle cx="54" cy="237" r="24" fill="#f1e9da" stroke="currentColor" strokeWidth="4"/><path d="m54 225 10 7-4 12H47l-4-12Z" fill="#171713"/></g></svg>}

export function HomeStory(){const root=useRef<HTMLDivElement>(null);useEffect(()=>{gsap.registerPlugin(ScrollTrigger);if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;const ctx=gsap.context(()=>{
  gsap.timeline({repeat:-1,yoyo:true,defaults:{ease:"sine.inOut"}}).to("[data-player]",{x:()=>Math.max(0,innerWidth-380),duration:6}).to("[data-player]",{scaleX:-1,duration:.01},">-.01");
  gsap.to("[data-ball]",{y:-18,duration:.45,repeat:-1,yoyo:true,ease:"power1.out"});
  gsap.timeline({scrollTrigger:{trigger:"[data-kick]",start:"top 70%",end:"bottom 25%",scrub:true}}).to("[data-kick-ball]",{scale:28,xPercent:45,yPercent:-20,ease:"power2.in"}).to("[data-work]",{opacity:1},"<70%");
  gsap.timeline({scrollTrigger:{trigger:"[data-case]",start:"top 75%",end:"center 40%",scrub:true}}).from("[data-file]",{x:(i)=>i%2?-160:160,y:-80,rotate:(i)=>i%2?10:-10}).from("[data-latch]",{scaleY:0,transformOrigin:"top"});
  gsap.from("[data-postcard]",{scrollTrigger:{trigger:"[data-music]",start:"top 80%",end:"center 55%",scrub:true},x:(i)=>[-140,120,-90][i]||0,y:-90,rotate:(i)=>[-8,7,-4][i]||0,opacity:0});
},root);return()=>ctx.revert()},[]);
return <div ref={root}>
 <section className={styles.hero}><div className="shell"><p className="eyebrow">Website builder / brand practitioner / left winger</p><h1 className="display">Ideas in motion.<br/>Systems that land.</h1><p className={styles.intro}>{profile.headline}</p></div><div className={styles.pitch}><div data-player className={styles.player}><Footballer/><strong>{profile.handle}</strong></div></div></section>
 <section data-kick className={styles.kick}><div data-kick-ball className={styles.wipeBall} aria-hidden="true"/><div className="shell"><p>Plant. Look up. Make the pass.</p></div></section>
 <section data-work className={`${styles.work} section`}><div className="shell"><p className="eyebrow">01 / Work in play</p><h2 className="display">A project-led practice.</h2><p className={styles.lead}>Website building, brand systems, content, SEO and practical digital operations across energy, professional services, hospitality and ecommerce.</p><div className={styles.workRows}>{profile.work.map(item=><article key={item.organization}><h3>{item.organization}</h3>{item.role&&<p className={styles.role}>{item.role}</p>}<p>{item.summary}</p></article>)}</div><div className={styles.github}><span>GitHub field note</span><p>Live contribution totals are not shown without an authenticated source.</p><a className="button" href={profile.social.github} target="_blank" rel="noreferrer">Open GitHub profile</a></div></div></section>
 <section data-case className={`${styles.caseScene} section`}><div className="shell"><p className="eyebrow">02 / Pack the work</p><div className={styles.caseFiles}>{profile.capabilities.map(x=><span data-file key={x}>{x}</span>)}</div><div className={styles.briefcase} aria-label="An illustrated briefcase closes to complete the work chapter"><div className={styles.handle}/><div className={styles.caseLid}/><div className={styles.caseBase}><i data-latch/><i data-latch/></div></div></div></section>
 <section className={`${styles.education} section`}><div className="shell"><p className="eyebrow">03 / Education</p><h2 className="display">Credentials, filed precisely.</h2><div className={styles.credentials}>{profile.education.map(item=><article key={item.credential}><p>{item.institution}</p><h3>{item.credential}</h3><p>{item.location}</p>{item.start&&item.end&&<time>{item.start.length===4?`${item.start} to ${item.end}`:"September 2024 to May 2025"}</time>}</article>)}</div></div></section>
 <section data-music className={`${styles.music} section`}><div className="shell"><p className="eyebrow">04 / After the lecture</p><h2 className="display">Postcards from the listening room.</h2><div className={styles.postcards}><article data-postcard><small>Side A</small><h3>A catalog, honestly quiet for now.</h3><p>No track URIs were supplied, so this release does not invent a playlist.</p></article><article data-postcard><small>Side B</small><h3>Playback stays with Spotify.</h3><p>Availability and account requirements are controlled by Spotify.</p></article><article data-postcard><small>Destination</small><h3>Pratham's profile</h3><a className="button dark" href={profile.social.spotify} target="_blank" rel="noreferrer">Open in Spotify</a></article></div></div></section>
 </div>}
